export const actionsOfTheDay = [
  { body: "Take a long walk outdoors" },
  { body: "Meet a new person" },
  { body: "Take a few minutes to breathe deeply and relax" },
  { body: "Call someone you care about" },
  { body: "Write down five positive things that happened to you today" },
  { body: "Write down five positive things about you" },
  { body: "Write down five positive things about someone you care about" },
  { body: "Write down five positive things about the life" },
  { body: "Listen to one of your favorite song and dance or sing like nobody's watching" },
  { body: "Prepare a healthy and balanced meal for yourself" },
  { body: "Switch off your electronic devices for an hour and engage in a technology-free activity" },
  { body: "Learn something new" },
  { body: "Go exercise" },
  { body: "Meditate" },
  { body: "Visit a new place" },
  { body: "Try a new activity or hobby that interests you" },
  { body: "Write a gratitude letter to someone who matters to you" },
  { body: "Help someone you care about" },
  { body: "Help a stranger" },
  { body: "Teach something to someone" },
  { body: "Work on a personal project" },
  { body: "Take a moment to appreciate nature around you" },
  { body: "Spend quality time with a loved one" },
  { body: "Practice random acts of kindness throughout the day" },
  { body: "Read a book or listen to an audiobook that inspires you" },
  { body: "Take a break from social media for a day" },

]